export const defaultData = [
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },
    {
        cierre: '',
        orden: 1234,
        'fecha creacion': 'sep 9, 2023',
        nombre: 'D30-AIRE MINI SPLIT',
        tipo: 'preventiva',
        'centro de costo': 'RM Don Rodrigo',
        'fecha ultima intervencion': 'ago 5, 2023',
        'fecha proxima intervencion': 'dic 9, 2023',
        componente: 'Aire minisplit',
        encargado: 'vidalviz avila',
        observacion: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
    },

    // {
    //     name: 'Marcus',
    //     lastName: 'Lawos',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Bertha',
    //     lastName: 'Clegain',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Martha',
    //     lastName: 'Gordom',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Luis',
    //     lastName: 'Foxcius',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Jerom',
    //     lastName: 'Maison',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Clara',
    //     lastName: 'Valezca',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Lei',
    //     lastName: 'Doggerti',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Lei',
    //     lastName: 'Valezca',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Luis',
    //     lastName: 'Doggerti',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Jerom',
    //     lastName: 'Maison',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Pedro',
    //     lastName: 'Wen',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Tanner',
    //     lastName: 'Linsley',
    //     age: 24,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Marcus',
    //     lastName: 'Lawos',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Bertha',
    //     lastName: 'Clegain',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Martha',
    //     lastName: 'Gordom',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Luis',
    //     lastName: 'Foxcius',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Jerom',
    //     lastName: 'Maison',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Clara',
    //     lastName: 'Valezca',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Lei',
    //     lastName: 'Doggerti',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Lei',
    //     lastName: 'Valezca',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Luis',
    //     lastName: 'Doggerti',
    //     age: 18,
    //     status: 'Activo',
    // },
    // {
    //     name: 'Jerom',
    //     lastName: 'Maison',
    //     age: 18,
    //     status: 'Inactivo',
    // },
    // {
    //     name: 'Pedro',
    //     lastName: 'Wen',
    //     age: 18,
    //     status: 'Activo',
    // },
]